---
- hosts: all
  become: true
  tasks:
    - name: install apache and PHP
      dnf:
        name:
          - "{{apa}}"
          - "{{php}}"
        state: absent
      #when: ansible_distribution == "fedora"
   
    - name: update repo
      dnf:
        update_cache: yes
      when: ansible_distribution == "fedora"
