---
- hosts: all
  become: true
  tasks:
    - name: install apache and PHP
      dnf:
        name:
          - "{{apa}}"
          - "{{php}}"
        state: latest
    - name: start httpd
      tags: start service httpd
      service:
        name: httpd
        state: started
      when: ansible_distribution == "fedora"
      
    - name: update repo
      dnf:
        update_cache: yes
      when: ansible_distribution == "fedora"
    - name: copy default html file for site
      tags: apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 644
