---
- hosts: all
  become: true
  tasks:
    - name: install apache and PHP
      dnf:
        name:
          - "{{apa}}"
          - "{{php}}"
        state: latest
    - name: start apache2
      tags: start service httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "fedora"

    - name: change email address for admin
      tags: apache,httpd, fedora
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: ;^ServerAdmin"
        line: ServerAdmin Satyam.xyz@gmail.com
        register: httpd

    - name: restart httpd (fedora)
      tags:apache (fedora)
      service:
        name: httpd
        state: restarted
      when: httpd.changed
      
    - name: update repo
      dnf:
        update_cache: yes
      when: ansible_distribution == "fedora"
    - name: copy default html file for site
      tags: apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 644

    - name: install apache and PHP
      apt:
        name:
          - "{{apa}}"
          - "{{php}}"
        state: latest
    - name: start apache2
      tags: start service apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "ubuntu"

    - name: change email address for admin
      tags: apache,ubuntu
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: ;^ServerAdmin"
        line: ServerAdmin Satyam.xyz@gmail.com
        register: apache

    - name: restart apache (apache)
      tags:apache (ubuntu)
      service:
        name: apache
        state: restarted
      when: apache.changed
      
    - name: update repo
      apt:
        update_cache: yes
      when: ansible_distribution == "ubuntu"
    - name: copy default html file for site
      tags: apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 644

